### ISSUE TITLE
Add pdf tutorial to site

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#31]
Add the pdf tutorial to the site

**Comment by KHBHH** [comment]
I have added a new tab named 'Help' to display the pdf tutorial file. Locally it works, because I have saved the file in www directory. When I deploy it to shiny server, the pdf does not show up. I assume that its not reading from the local drive. I was thinking is it possible to have this pdf file linked to a link as such "https://storage.googleapis.com/googleGuideChrome.pdf" as we did with the genomes, when we put it on google drive?

**Comment by alosdiallo** [comment]
Yes.  Email it to me and I will add it.

**Comment by KHBHH** [comment]
I emailed the tutorial to you

**Comment by KHBHH** [comment]
I added the pdf to the tab (**Help**). It works now.

**Comment by alosdiallo** [comment]
Closing
