### ISSUE TITLE
The pdf fails to load when I click on the help button.

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#34]
The pdf fails to load when I click on the help button.
![pdf_fail](https://user-images.githubusercontent.com/3083525/58115777-ce84dc00-7bc8-11e9-89e1-f1be210d7dfd.png)

**Comment by KHBHH** [comment]
Yes, because it's reading from the local drive (www directory). That's why I wanted to put it as a link in google drive as we did for the genomes. I know you mentioned about the budget there; not to have many file in there. But would it be possible if you can make the pdf tutorial as a link? (As I mentioned in the email)

**Comment by KHBHH** [comment]
Yes, because it is reading from the local drive (www directory). Would it be possible to have this tutorial in google drive as a link (like the genomes), as mentioned in my email? I know you replied to be careful about the budget, but right now this is the solution that I am thinking about. Because saving in the **www** directory works locally, when I deploy it to shiny server, it fails.

**Comment by alosdiallo** [comment]
Yes. Please email it to me and I will upload it.

**Comment by KHBHH** [comment]
sent the tutorial via email

**Comment by alosdiallo** [comment]
https://storage.googleapis.com/gencode_ch_data/DNA_Rchitect_Tutorial.pdf

**Comment by KHBHH** [comment]
This works now.
