### ISSUE TITLE
Make sure interactive tutorial works

### ISSUE THREAD

**Issue by alosdiallo** [alosdiallo/HiC_Network_Viz_tool#36]
Run through the interactive tutorial and make sure it works

**Comment by KHBHH** [comment]
I have the following comments:

1) In **step3: Click to add or remove data types**  I am not sure what should this refer to!
2) Maybe we can add a step after step 5, to show that the user can use sample data.
3) I think step 23 & 24 should be removed. Because we have changed the cytoscape network and have removed the box that used to show selected nodes.

**Comment by alosdiallo** [comment]
Can you email Simon and ask him how to edit this?

**Comment by KHBHH** [comment]
I was already going to ask you how to edit this. So I will email him now.

**Comment by alosdiallo** [comment]
I only have Simon's HMS email.  Try that.

**Comment by alosdiallo** [comment]
Here is the code that controls that:
https://github.com/alosdiallo/DNA_Rchitect/blob/master/App/www/js/intro.js
